In [2]:
import pandas as pd

print("ok")

ok

In [5]:
## pandas series is one-dimentional array..

data  = [1,2,3,4,5]

series = pd.Series(data)
print("Series: \n", series)

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
data2 = {'a':1, 'b':2, 'c':3}

d = pd.Series(data2)
print(d)

a    1
b    2
c    3
dtype: int64

In [10]:
data3 = [10,20,30,40,50,60]
indx = ['a,', 'b','c', 'd', 'e','f']
s = pd.Series(data3, index=indx)
print(s)

a,    10
b     20
c     30
d     40
e     50
f     60
dtype: int64

In [11]:
## Dataframe ( multiple rows and columns...)

## create a dataframe from a dictionary of list..

data = {
    'name':['krish', 'anuj', 'madhav'],
    'Age':[33,44,23],
    'City':['indore', 'banglore', 'mumbai']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

     name  Age      City
0   krish   33    indore
1    anuj   44  banglore
2  madhav   23    mumbai
<class 'pandas.DataFrame'>

In [40]:
## Create a DataFrame from the dictionary of list..

data = [
    {'name':'anuj', 'age':43, 'city':"kanpur"},
    {'name':'tom', 'age':34, 'city':"mumbai"},
    {'name':'Jack', 'age':24, 'city':"bhopal"},
]

t = pd.DataFrame(data)
print(t)

   name  age    city
0  anuj   43  kanpur
1   tom   34  mumbai
2  Jack   24  bhopal

In [41]:
csv_data = pd.read_csv('sample_data.csv')
# csv_data.head(5)

In [42]:
# last 5 records by tail function

# pd.tail(5)

In [43]:
t.loc[0]

name      anuj
age         43
city    kanpur
Name: 0, dtype: object

In [44]:
t.at[2,'age']

np.int64(24)

In [45]:
t.iat[1,2]

'mumbai'

In [46]:
t.drop('city', axis=1)

   name  age
0  anuj   43
1   tom   34
2  Jack   24

In [47]:
t['age'] = t['age'] +10

In [48]:
t

   name  age    city
0  anuj   53  kanpur
1   tom   44  mumbai
2  Jack   34  bhopal

In [49]:
csv_data.describe()

,Scan Number,3001 (°C)- TC1B,3002 (°C)- TC2B,3003 (°C)- TC3B,3004 (°C)- TC4B,3005 (°C)- TC5B,3006 (°C)- TC6B,3007 (°C)- TC7B,3008 (°C)- TC8B,3009 (°C)- TC9B,...,7002 (Vdc)- HF2 C1 NE CORNER,7003 (Vdc)- HF3 C4 DUAL1,7004 (Vdc)- HF4 C4 ARC2,7005 (Vdc)- HF5 C3 ARC1,7006 (Vdc)- HF6 C1 N FRONT L,7007 (Vdc)- HF7 WALL,7008 (Vdc)- HF8 C3 ARC1,7009 (Vdc)- HF9 C3 ARC2,7010 (Vdc)- HF10 C3 DUAL1,7011 (Vdc)- HF11 C2 DUAL1
count,12580.000000,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,...,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,12580.000000,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04
mean,6290.500000,5.744833e+35,5.902226e+35,6.217011e+35,4.328299e+35,5.351351e+35,4.328299e+35,4.879173e+35,4.564388e+35,4.249603e+35,...,-2.024177e-04,1.168544e-04,7.147749e-05,1.514815e-04,0.007093,2.073259e-04,4.877711e-05,1.022017e-04,1.455226e-04,7.473918e-05
std,3631.677528,7.519861e+36,7.621567e+36,7.820918e+36,6.531938e+36,7.259215e+36,6.531938e+36,6.933222e+36,6.706913e+36,6.472542e+36,...,1.256950e-02,1.336237e-02,2.236573e-03,6.185218e-03,0.044186,2.880065e-03,1.435319e-03,3.310421e-03,2.641377e-03,1.571022e-03
min,1.000000,-1.238020e+02,-1.975290e+02,-1.767940e+02,-1.752830e+02,-8.634200e+01,1.551500e+01,-7.833000e+00,1.533600e+01,-1.409090e+02,...,-1.016338e+00,-5.692921e-01,-1.118398e-01,-1.946402e-03,-1.192363,-1.006645e-01,-1.139135e-01,-5.603114e-02,-8.037980e-02,-1.232640e-04
25%,3145.750000,1.740350e+01,2.057900e+01,2.440600e+01,1.995500e+01,1.921050e+01,1.994475e+01,1.937800e+01,1.980400e+01,2.065000e+01,...,-1.068000e-06,-1.068000e-06,-6.790000e-07,-5.820000e-07,0.001107,3.880000e-07,-5.820000e-07,-6.790000e-07,-1.068000e-06,-7.760000e-07
50%,6290.500000,1.953300e+01,2.315700e+01,2.783500e+01,2.359850e+01,2.011500e+01,2.714300e+01,2.540950e+01,2.090850e+01,2.211050e+01,...,-5.820000e-07,-6.790000e-07,-2.910000e-07,-1.940000e-07,0.007416,9.710000e-07,-2.910000e-07,-2.910000e-07,-4.850000e-07,-2.910000e-07
75%,9435.250000,1.083465e+02,1.210045e+02,1.214988e+02,1.079340e+02,3.162950e+01,4.469475e+01,3.456850e+01,4.811800e+01,3.507200e+01,...,-9.700000e-08,-2.910000e-07,0.000000e+00,9.700000e-08,0.013324,1.747000e-06,9.700000e-08,0.000000e+00,-9.700000e-08,2.910000e-07
max,12580.000000,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,...,7.005935e-02,8.643902e-01,4.582471e-02,5.522392e-01,0.330207,7.378318e-02,4.481269e-02,1.789245e-01,1.518688e-01,8.536144e-02

In [8]:
import pandas as pd
name_data = [{'name':"harish", 'age':23, 'city':'indore'}, {'name':"punit", 'age':53, 'city':'bhopal'}, {'name':"govind", 'age':32, 'city':'pune'}]

dff = pd.DataFrame(name_data)

print(dff)
dff['age'] = dff['age']+5
dff

     name  age    city
0  harish   23  indore
1   punit   53  bhopal
2  govind   32    pune

     name  age    city
0  harish   28  indore
1   punit   58  bhopal
2  govind   37    pune